server:
  port: 2022

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/certificadazo}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8080/realms/certificadazo/protocol/openid-connect/certs}
  
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
              filters:
                - TokenRelay=
                - StripPrefix=1

            - id: users-service
              uri: lb://users-service
              predicates:
                - Path=/api/users/**
              filters:
                - TokenRelay=
                - StripPrefix=1

            - id: departments-service
              uri: lb://departments-service
              predicates:
                - Path=/api/departments/**
              filters:
                - TokenRelay=
                - StripPrefix=1
            - id: templates-service
              uri: lb://templates-service
              predicates:
                - Path=/api/templates/**
              filters:
                - TokenRelay=
                - StripPrefix=1

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka