server:
  port: ${PORT:0}

spring:
  application:
    name: templates-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3302/templates-db?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:judadev}
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    function:
      definition: handleCommands

    stream:
      bindings:
        handleCommands-in-0:
          destination: templates-events
          content-type: application/json
          group: templates-service
        handleCommands-out-0:
          destination: ai-replies
          content-type: application/json

      kafka:
        binder:
          brokers: ${KAFKA_URI:localhost:9092}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
